packages:
  - apps/*
  - packages/*
catalog:
  '@eslint/js': ^9.21.0
  '@next/eslint-plugin-next': ^15.1.6
  '@tailwindcss/postcss': ^4.0.9
  '@types/node': ^20
  '@types/react': ^19.0.7
  '@types/react-dom': ^19.0.3
  next: ^15.1.6
  react: ^19.0.0
  react-dom: ^19.0.0
  autoprefixer: ^10.4.20
  eslint: ^9.21.0
  postcss: ^8.5.1
  tailwindcss: ^4.0.0
  typescript: 5.7.3
